This folder is for debugging LED, to overwrite encoder to add positional encoding

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys

sys.path.append('/home/alta/Conversational/OET/al826/2022/seq_cls')

In [3]:
from src.models.hugging_utils import get_transformer
from src.models.models import TransformerHead, Seq2SeqWrapper, SequenceTransformer

model = get_transformer('led')
model = Seq2SeqWrapper.wrap(model, 2)
model.set_setting(['reset_enc_pos'])


tensor([[ 0.0046, -0.0624,  0.0081, -0.1458, -0.0070],
        [ 0.0217, -0.0440,  0.0213, -0.0821,  0.0196]],
       grad_fn=<SliceBackward>)
tensor([[-0.0657,  0.0665, -0.0143, -0.0035, -0.0443],
        [-0.0296, -0.0099, -0.0288,  0.2861,  0.0173]],
       grad_fn=<SliceBackward>)
resetting encoder positional embeddings
tensor([[ 0.6609, -0.6226,  0.7483,  0.3327, -1.0561],
        [ 1.1383, -0.8382, -1.3715, -0.9782,  0.9518]],
       grad_fn=<SliceBackward>)
tensor([[-0.0657,  0.0665, -0.0143, -0.0035, -0.0443],
        [-0.0296, -0.0099, -0.0288,  0.2861,  0.0173]],
       grad_fn=<SliceBackward>)
tensor([[ 0.0046, -0.0624,  0.0081, -0.1458, -0.0070],
        [ 0.0217, -0.0440,  0.0213, -0.0821,  0.0196]],
       grad_fn=<SliceBackward>)
tensor([[-0.0657,  0.0665, -0.0143, -0.0035, -0.0443],
        [-0.0296, -0.0099, -0.0288,  0.2861,  0.0173]],
       grad_fn=<SliceBackward>)
resetting encoder positional embeddings
tensor([[ 0.2467,  0.1574,  0.2944, -1.3233, -0.1715],
       

In [4]:
asd

NameError: name 'asd' is not defined

In [ ]:
from transformers import LEDTokenizerFast, LEDForConditionalGeneration 

transformer = LEDForConditionalGeneration.from_pretrained("allenai/led-base-16384", return_dict=True)
transformer.__dict__['_modules']['model'] = transformer.__dict__['_modules']['led']


In [ ]:
from src.models.models import Seq2SeqWrapper
model = Seq2SeqWrapper.wrap(transformer, 43)
model.set_setting('utt_encoder')

In [ ]:
from src.helpers import ConvHandler, Batcher
from src.config import config

C = ConvHandler(system='led', punct=False, action=False, hes=False)
batcher = Batcher(mode='seq2seq', num_labels=43, max_len=None, mode_args=None)

test_path = f"{config.base_dir}/data/swda/standard/test.json"
eval_data = C.prepare_data(path=test_path, lim=100)
eval_convs = batcher.eval_batches(eval_data)
        

In [ ]:
from src.models.models import Seq2SeqWrapper

for batch in eval_convs:
    output = model(input_ids=batch.ids, 
                   attention_mask=batch.mask, 
                   labels=batch.labels)
    loss = output.loss
    y    = output.logits
    

In [ ]:
import torch

a = [[1,2,7,1,2,3,2,1,3,1,5,6,1],[2,2,7,1,2,3,2,1,3,1,5,6,1]]
a = torch.Tensor(a)

b = (a==1)
c = torch.cumsum(b, -1)

print(c)

In [ ]:
print(b.__class__.__bases__)