This folder is for debugging LED, to overwrite encoder to add positional encoding

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys

sys.path.append('/home/alta/Conversational/OET/al826/2022/seq_cls')

In [3]:
from transformers import LEDTokenizerFast, LEDForConditionalGeneration 

transformer = LEDForConditionalGeneration.from_pretrained("allenai/led-base-16384", return_dict=True)
transformer.__dict__['_modules']['model'] = transformer.__dict__['_modules']['led']


In [11]:
from src.models.models import Seq2SeqWrapper
model = Seq2SeqWrapper.wrap(transformer, 43)
model.set_setting('utt_encoder')

In [6]:
from src.helpers import ConvHandler, Batcher
from src.config import config

C = ConvHandler(system='led', punct=False, action=False, hes=False)
batcher = Batcher(mode='seq2seq', num_labels=43, max_len=None, mode_args=None)

test_path = f"{config.base_dir}/data/swda/standard/test.json"
eval_data = C.prepare_data(path=test_path, lim=100)
eval_convs = batcher.eval_batches(eval_data)
        

100%|██████████| 19/19 [00:00<00:00, 62.67it/s]


In [14]:
from src.models.models import Seq2SeqWrapper

for batch in eval_convs:
    output = model(input_ids=batch.ids, 
                   attention_mask=batch.mask, 
                   labels=batch.labels)
    loss = output.loss
    y    = output.logits
    

og positonal embedding shape torch.Size([2048, 768])
torch.Size([1, 2048])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1, 2048, 768])
tensor([[-0.0657,  0.0665, -0.0143, -0.0035, -0.0443],
        [-0.0657,  0.0665, -0.0143, -0.0035, -0.0443],
        [-0.0657,  0.0665, -0.0143, -0.0035, -0.0443],
        [-0.0657,  0.0665, -0.0143, -0.0035, -0.0443],
        [-0.0657,  0.0665, -0.0143, -0.0035, -0.0443],
        [-0.0657,  0.0665, -0.0143, -0.0035, -0.0443],
        [-0.0657,  0.0665, -0.0143, -0.0035, -0.0443],
        [-0.0657,  0.0665, -0.0143, -0.0035, -0.0443],
        [-0.0657,  0.0665, -0.0143, -0.0035, -0.0443],
        [-0.0296, -0.0099, -0.0288,  0.2861,  0.0173],
        [-0.0296, -0.0099, -0.0288,  0.2861,  0.0173],
        [-0.0296, -0.0099, -0.0288,  0.2861,  0.0173],
        [-0.0296, -0.0099, -0.0288,  0.2861,  0.0173],
        [-0.0296, -0.0099, -0.0288,  0.2861,  0.0173],
        [-0.0296, -0.0099, -0.0288,  0.2861,  0.0173],
    

og positonal embedding shape torch.Size([2048, 768])
torch.Size([1, 2048])
tensor([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])
torch.Size([1, 2048, 768])
tensor([[-0.0657,  0.0665, -0.0143, -0.0035, -0.0443],
        [-0.0657,  0.0665, -0.0143, -0.0035, -0.0443],
        [-0.0657,  0.0665, -0.0143, -0.0035, -0.0443],
        [-0.0657,  0.0665, -0.0143, -0.0035, -0.0443],
        [-0.0296, -0.0099, -0.0288,  0.2861,  0.0173],
        [-0.0296, -0.0099, -0.0288,  0.2861,  0.0173],
        [-0.0296, -0.0099, -0.0288,  0.2861,  0.0173],
        [-0.0296, -0.0099, -0.0288,  0.2861,  0.0173],
        [-0.0098,  0.0582,  0.0123, -0.1298, -0.0012],
        [-0.0098,  0.0582,  0.0123, -0.1298, -0.0012],
        [-0.0098,  0.0582,  0.0123, -0.1298, -0.0012],
        [-0.0098,  0.0582,  0.0123, -0.1298, -0.0012],
        [-0.0098,  0.0582,  0.0123, -0.1298, -0.0012],
        [-0.0098,  0.0582,  0.0123, -0.1298, -0.0012],
        [-0.0098,  0.0582,  0.0123, -0.1298, -0.0012],
    

og positonal embedding shape torch.Size([4096, 768])
torch.Size([1, 4096])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1, 4096, 768])
tensor([[-0.0657,  0.0665, -0.0143, -0.0035, -0.0443],
        [-0.0657,  0.0665, -0.0143, -0.0035, -0.0443],
        [-0.0657,  0.0665, -0.0143, -0.0035, -0.0443],
        [-0.0657,  0.0665, -0.0143, -0.0035, -0.0443],
        [-0.0657,  0.0665, -0.0143, -0.0035, -0.0443],
        [-0.0657,  0.0665, -0.0143, -0.0035, -0.0443],
        [-0.0657,  0.0665, -0.0143, -0.0035, -0.0443],
        [-0.0657,  0.0665, -0.0143, -0.0035, -0.0443],
        [-0.0657,  0.0665, -0.0143, -0.0035, -0.0443],
        [-0.0296, -0.0099, -0.0288,  0.2861,  0.0173],
        [-0.0296, -0.0099, -0.0288,  0.2861,  0.0173],
        [-0.0296, -0.0099, -0.0288,  0.2861,  0.0173],
        [-0.0296, -0.0099, -0.0288,  0.2861,  0.0173],
        [-0.0296, -0.0099, -0.0288,  0.2861,  0.0173],
        [-0.0296, -0.0099, -0.0288,  0.2861,  0.0173],
    

In [ ]:
import torch

a = [[1,2,7,1,2,3,2,1,3,1,5,6,1],[2,2,7,1,2,3,2,1,3,1,5,6,1]]
a = torch.Tensor(a)

b = (a==1)
c = torch.cumsum(b, -1)

print(c)

In [ ]:
print(b.__class__.__bases__)